service: message-all-users
provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: 'eu-west-2'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - arn:aws:secretsmanager:eu-west-2:927304557361:secret:message-all-users/secrets-AQrsHg







functions:
  message-all:
    handler: main.lambda_handler

plugins:
  - serverless-python-requirements